// — TourLive Design Tokens —
const W = '#FFFFFF';        // Gray.0 / text.inverse
const ORANGE = '#FF730D';   // Orange.500 / primary.default
const ORANGE_HOVER = '#FF5811'; // Orange.600 / primary.hover
const ORANGE_LIGHT = '#FFF3EC'; // Orange.100 / primary.light
const TXT_STRONG = '#1A1A1A';  // Gray.800
const TXT_DEFAULT = '#3A3A3A'; // Gray.700
const TXT_SUBTLE = '#8A8A8A';  // Gray.600
const TXT_DISABLED = '#A0A0A0'; // Gray.500
const BG_PAGE = '#FFFFFF';     // Gray.0
const BG_SUBTLE = '#F9F9F9';   // Gray.100
const BG_MUTED = '#F2F4F7';    // Gray.200
const BORDER_DEFAULT = '#D1D1D1'; // Gray.400
const SUB_COLOR = '#475569';   // Slate.600 / 전환(길찾기) 핀
const PLAYER_BG = '#000000';   // Gray.900
const FONT = "'Pretendard Variable', 'Pretendard', -apple-system, BlinkMacSystemFont, sans-serif";
const styles = {
  root: { position: 'relative', height: '100%', minHeight: 0, background: PLAYER_BG, overflow: 'hidden', color: W,
    fontFamily: FONT },

  player: { position: 'absolute', top: 0, left: 0, right: 0, display: 'flex', flexDirection: 'column',
    background: PLAYER_BG, overflow: 'hidden' },
  topBar: { position: 'relative', zIndex: 2, display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '10px 16px', background: 'linear-gradient(rgba(0,0,0,0.45), transparent)' },
  iconBtn: { background: 'none', border: 'none', color: W, fontSize: 24, lineHeight: 1, cursor: 'pointer', width: 32, height: 32, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 0 },
  topRight: { display: 'flex', alignItems: 'center', gap: 8 },
  topChip: { display: 'flex', alignItems: 'center', gap: 4, background: 'rgba(255,255,255,0.15)',
    border: 'none', color: W, fontSize: 12, padding: '5px 10px', borderRadius: 9999,
    cursor: 'pointer', whiteSpace: 'nowrap' },
  gearBtn: { background: 'none', border: 'none', color: W, fontSize: 18,
    width: 36, height: 36, borderRadius: 9999, cursor: 'pointer',
    display: 'flex', alignItems: 'center', justifyContent: 'center' },

  // 풀 플레이어
  fullWrap: { flex: 1, display: 'flex', flexDirection: 'column', padding: '4px 20px 16px', overflow: 'auto' },
  artBig: { position: 'relative', width: '80%', aspectRatio: '1 / 1', margin: '6px auto 0', borderRadius: 8, overflow: 'hidden',
    background: '#2a2a2a', boxShadow: '0 12px 40px rgba(0,0,0,0.6)' },
  artImg: { width: '100%', height: '100%', objectFit: 'contain' },
  coverImg: { position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover' },
  containImg: { position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'contain' },
  miniBlurBg: { position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover', filter: 'blur(28px)', transform: 'scale(1.2)', opacity: 0.5 },
  imgFallback: { width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center',
    background: 'linear-gradient(135deg,#2a2a32,#16161c)' },
  imgFallbackIcon: { fontSize: 40, opacity: 0.5 },
  playOverlay: { position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: 40, color: 'rgba(255,255,255,0.85)', textShadow: '0 2px 12px rgba(0,0,0,0.6)', pointerEvents: 'none' },
  carouselDots: { position: 'absolute', bottom: 8, left: 0, right: 0, display: 'flex', justifyContent: 'center', gap: 5, pointerEvents: 'auto' },
  carouselDot: { width: 6, height: 6, borderRadius: '50%', background: 'rgba(255,255,255,0.45)', cursor: 'pointer' },
  carouselDotOn: { background: '#fff', transform: 'scale(1.3)' },
  badge: { position: 'absolute', top: 8, left: 8, background: ORANGE, color: W, fontSize: 11, fontWeight: 600,
    padding: '3px 8px', borderRadius: 9999, letterSpacing: '0.04em' },
  countRow: { textAlign: 'left', margin: '12px 0 4px' },
  count: { fontSize: 13, color: TXT_SUBTLE },
  titleRow: { display: 'flex', alignItems: 'flex-start', gap: 12, marginTop: 4 },
  title: { fontSize: 20, fontWeight: 600, color: W, margin: 0, lineHeight: 1.45, textAlign: 'left' },
  subtitle: { fontSize: 13, color: TXT_SUBTLE, margin: '4px 0 0', lineHeight: 1.5, textAlign: 'left' },
  heart: { background: 'none', border: 'none', fontSize: 24, cursor: 'pointer', lineHeight: 1, flexShrink: 0 },
  desc: { fontSize: 14, lineHeight: 1.55, color: TXT_SUBTLE, marginTop: 12 },

  chips: { display: 'flex', gap: 8, marginTop: 16, flexWrap: 'wrap' },
  chip: { fontSize: 13, color: W, background: 'rgba(255,255,255,0.15)', padding: '8px 12px',
    borderRadius: 8, whiteSpace: 'nowrap', border: 'none', cursor: 'pointer',
    backdropFilter: 'blur(10px)', WebkitBackdropFilter: 'blur(10px)' },
  chipIcon: { color: W, background: 'none', border: 'none', width: 36, height: 36,
    borderRadius: 9999, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' },

  progWrap: { marginTop: 16 },
  progBar: { position: 'relative', height: 4, background: 'rgba(255,255,255,0.15)', borderRadius: 9999, cursor: 'pointer' },
  progFill: { position: 'absolute', top: 0, left: 0, height: '100%', background: ORANGE, borderRadius: 9999 },
  progThumb: { position: 'absolute', top: '50%', transform: 'translate(-50%,-50%)', width: 12, height: 12, borderRadius: '50%',
    background: '#fff', pointerEvents: 'none' },
  timeRow: { display: 'flex', justifyContent: 'space-between', marginTop: 7 },
  time: { fontSize: 12, color: TXT_SUBTLE },

  controls: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 20, marginTop: 16 },
  ctrlSide: { background: 'none', border: 'none', color: TXT_SUBTLE, fontSize: 20, cursor: 'pointer',
    display: 'flex', alignItems: 'center' },
  ctrlNum: { fontSize: 9, bottom: 0 },
  ctrl: { background: 'none', border: 'none', color: W, fontSize: 22, cursor: 'pointer' },
  ctrlBig: { background: 'none', border: 'none', color: W, fontSize: 26, cursor: 'pointer' },
  play: { width: 48, height: 48, borderRadius: '50%', background: W, color: PLAYER_BG, fontSize: 18, cursor: 'pointer',
    display: 'flex', alignItems: 'center', justifyContent: 'center', border: 'none' },
  playBig: { width: 64, height: 64, borderRadius: '50%', background: W, color: PLAYER_BG, fontSize: 24, cursor: 'pointer',
    display: 'flex', alignItems: 'center', justifyContent: 'center', border: 'none' },
  playDisabled: { background: 'rgba(255,255,255,0.25)', color: 'rgba(255,255,255,0.6)' },

  bottomBtns: { display: 'flex', gap: 8, marginTop: 'auto', paddingTop: 20 },
  bottomBtn: { flex: 1, padding: '14px', borderRadius: 12, background: 'rgba(255,255,255,0.15)',
    border: 'none', color: W, fontSize: 15, fontWeight: 600, cursor: 'pointer' },

  // 90% 컴팩트 바
  compactBar: { display: 'flex', alignItems: 'center', gap: 12, padding: '8px 16px',
    background: PLAYER_BG, flex: 1, overflow: 'hidden' },
  compactThumb: { position: 'relative', width: 52, height: 52, borderRadius: 8, overflow: 'hidden', flexShrink: 0,
    background: '#222' },
  compactTitleWrap: { flex: 1, overflow: 'hidden' },
  compactTitle: { display: 'inline-block', fontSize: 16, fontWeight: 700, color: W,
    whiteSpace: 'nowrap', animation: 'marquee 8s linear infinite', animationDelay: '2s' },
  compactControls: { display: 'flex', alignItems: 'center', gap: 8, flexShrink: 0 },
  compactPlayBtn: { width: 40, height: 40, borderRadius: '50%', background: 'rgba(255,255,255,0.15)',
    color: W, fontSize: 16, border: 'none', cursor: 'pointer',
    display: 'flex', alignItems: 'center', justifyContent: 'center' },
  compactDownBtn: { width: 40, height: 40, borderRadius: '50%', background: 'rgba(255,255,255,0.15)',
    color: W, fontSize: 24, border: 'none', cursor: 'pointer',
    display: 'flex', alignItems: 'center', justifyContent: 'center', lineHeight: 1 },

  // 미니 플레이어
  miniWrap: { position: 'absolute', inset: 0, zIndex: 1, background: PLAYER_BG },
  miniBar: { position: 'absolute', left: 0, right: 0, bottom: 0, display: 'flex', alignItems: 'center',
    padding: '12px 16px', gap: 12, background: 'linear-gradient(transparent, rgba(0,0,0,0.7))' },
  miniBarInfo: { flex: 1, display: 'flex', flexDirection: 'column', gap: 2, overflow: 'hidden', textAlign: 'left' },
  miniBarTitle: { fontSize: 15, fontWeight: 700, color: W, whiteSpace: 'nowrap',
    textShadow: '0 1px 4px rgba(0,0,0,0.5)', display: 'inline-block',
    animation: 'marquee 8s linear infinite', animationDelay: '2s' },
  miniBarSub: { fontSize: 12, color: 'rgba(255,255,255,0.7)', whiteSpace: 'nowrap' },
  miniBarControls: { display: 'flex', alignItems: 'center', gap: 8, flexShrink: 0 },
  miniBarBtn: { background: 'none', border: 'none', color: W, fontSize: 20, cursor: 'pointer',
    width: 36, height: 36, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  miniBarPlay: { width: 40, height: 40, borderRadius: '50%', background: W, color: PLAYER_BG,
    fontSize: 16, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', border: 'none' },

  // 시트
  sheet: { position: 'absolute', left: 0, right: 0, bottom: 0, background: BG_MUTED, borderRadius: '16px 16px 0 0',
    display: 'flex', flexDirection: 'column', overflow: 'hidden', boxShadow: '0 -4px 12px rgba(0,0,0,0.3)' },
  handleZone: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: 20, cursor: 'grab',
    touchAction: 'none', flexShrink: 0 },
  sheetTabBar: { display: 'flex', alignItems: 'center', padding: '6px 14px 6px', flexShrink: 0 },
  sheetTabToggle: { display: 'flex', background: BG_MUTED, borderRadius: 9999, padding: 3, gap: 2,
    border: `1px solid ${BORDER_DEFAULT}` },
  sheetTabToggleFixed: { position: 'absolute', right: 16, bottom: 16, zIndex: 20, display: 'flex',
    background: BG_PAGE, borderRadius: 9999, padding: 3, gap: 2,
    border: `1px solid ${BORDER_DEFAULT}`, boxShadow: '0 2px 8px rgba(0,0,0,0.15)' },
  sheetTabBtn: { height: 34, padding: '0 12px', borderRadius: 9999, border: 'none', background: 'transparent',
    fontSize: 13, fontWeight: 600, color: TXT_SUBTLE, cursor: 'pointer', whiteSpace: 'nowrap', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  sheetTabBtnOn: { background: '#1a1a1a', color: '#fff', boxShadow: '0 1px 6px rgba(0,0,0,0.2)' },
  grabber: { width: 52, height: 6, borderRadius: 9999, background: BORDER_DEFAULT },
  mapTopBar: { position: 'absolute', top: 10, left: 10, right: 10, zIndex: 5, display: 'flex', gap: 8,
    flexWrap: 'wrap' },
  // 목차 상단바 (지도 시트와 동일: 이름 드롭다운 + 토글)
  listTopRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '10px 12px 8px', background: BG_MUTED },

  // 지도 시트 헤더 바 (이름 드롭다운 + 토글) — 시트와 같은 색 배경
  mapHeaderBar: { position: 'absolute', top: 0, left: 0, right: 0, zIndex: 8,
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '10px 12px', background: BG_MUTED },

  // 지도 상단 좌측: 지도 이름 드롭다운
  mapNameBtn: { display: 'flex', alignItems: 'center', gap: 4, height: 36, padding: '0 8px',
    borderRadius: 9999, border: 'none', background: BG_MUTED, color: TXT_STRONG,
    fontSize: 14, fontWeight: 700, cursor: 'pointer', outline: 'none' },
  mapNameMenu: { position: 'absolute', top: 42, left: 0, minWidth: 160, background: BG_PAGE,
    borderRadius: 12, overflow: 'hidden', boxShadow: '0 6px 20px rgba(0,0,0,0.2)',
    border: `1px solid ${BORDER_DEFAULT}` },
  mapNameItem: { display: 'block', width: '100%', padding: '12px 14px', textAlign: 'left',
    border: 'none', borderBottom: `1px solid ${BG_MUTED}`, background: 'none',
    fontSize: 14, fontWeight: 500, color: TXT_DEFAULT, cursor: 'pointer', whiteSpace: 'nowrap', outline: 'none' },
  mapNameItemOn: { color: ORANGE, fontWeight: 700, background: ORANGE_LIGHT },

  tocBtn: { height: 34, padding: '0 12px', borderRadius: 9999,
    background: TXT_STRONG, color: W, fontSize: 13, fontWeight: 700, border: 'none', cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(0,0,0,0.28)', display: 'flex', alignItems: 'center', outline: 'none' },
  mapTopBtn: { height: 34, padding: '0 12px', borderRadius: 9999, border: `1px solid ${BORDER_DEFAULT}`,
    background: BG_PAGE, color: TXT_STRONG, fontSize: 13, fontWeight: 600, cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(0,0,0,0.08)', display: 'flex', alignItems: 'center', outline: 'none' },
  mapIconBtn: { width: 34, height: 34, padding: 0, borderRadius: 9999, border: `1px solid ${BORDER_DEFAULT}`,
    background: BG_PAGE, color: TXT_STRONG, cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(0,0,0,0.08)', display: 'flex', alignItems: 'center', justifyContent: 'center', outline: 'none' },
  mapTopBtnOn: { background: '#334155', border: '1.5px solid #334155', color: W },
  listWrap: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minHeight: 0 },
  listHeader: { flexShrink: 0, background: BG_MUTED },
  listTopBarOuter: { display: 'flex', alignItems: 'center', padding: '10px 12px 6px',
    background: BG_MUTED, gap: 4 },
  listTopBar: { display: 'flex', alignItems: 'center', gap: 8, flex: 1,
    overflowX: 'auto', flexWrap: 'nowrap', WebkitOverflowScrolling: 'touch',
    scrollbarWidth: 'none', msOverflowStyle: 'none' },
  listSecondBar: { display: 'flex', alignItems: 'center', gap: 8,
    padding: '0 12px 8px', background: BG_MUTED },
  floorHamburgerBtn: { flexShrink: 0, width: 34, height: 34, borderRadius: 9999,
    border: `1px solid ${BORDER_DEFAULT}`, background: BG_PAGE, cursor: 'pointer',
    display: 'flex', alignItems: 'center', justifyContent: 'center', outline: 'none' },
  searchBtn: { width: 38, height: 38, borderRadius: 10, border: `1px solid ${BORDER_DEFAULT}`,
    background: BG_PAGE, display: 'flex', alignItems: 'center', justifyContent: 'center',
    cursor: 'pointer', flexShrink: 0 },
  searchIconAbsBtn: { flexShrink: 0, width: 36, height: 36, border: 'none', background: 'none',
    display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', outline: 'none' },
  searchIconBtn: { width: 36, height: 36, border: 'none', background: 'none',
    display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', flexShrink: 0, outline: 'none' },
  searchBar: { flex: 1, display: 'flex', alignItems: 'center', gap: 8, height: 38,
    border: `1.5px solid ${ORANGE}`, borderRadius: 9999, padding: '0 14px', background: BG_PAGE },
  searchInput: { flex: 1, border: 'none', outline: 'none', background: 'none',
    fontSize: 14, color: TXT_STRONG, fontFamily: 'inherit' },
  searchCancelBtn: { flexShrink: 0, border: 'none', background: 'none', fontSize: 14,
    fontWeight: 500, color: TXT_DEFAULT, cursor: 'pointer', outline: 'none', padding: '0 4px' },
  tocBtnList: { height: 34, padding: '0 12px', borderRadius: 9999, background: TXT_STRONG, color: W, fontSize: 13, fontWeight: 700,
    border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', outline: 'none' },

  sheetBody: { position: 'relative', flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minHeight: 0 },
  mapBox: { position: 'relative', flex: 1, overflow: 'hidden', minHeight: 0, background: '#E3E3E3' },
  stripOverlay: { position: 'absolute', left: 0, right: 0, bottom: 0, zIndex: 5, padding: '8px 16px 16px',
    background: 'linear-gradient(transparent, rgba(255,255,255,0.96) 46%, rgb(255,255,255) 68%)' },
  pinActionBar: { display: 'flex', gap: 8, padding: '8px 0 4px' },

  // 층 도면
  floorWrap: { position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column' },
  mapTrackCard: { position: 'absolute', top: 8, left: 8, right: 8, zIndex: 7 },
  // 스크롤 없이 한 화면에: 도면을 박스 안에 맞춰 표시(정사각 캔버스, 중앙 정렬)
  floorImgBox: { position: 'relative', flex: 1, overflow: 'hidden', background: '#E3E3E3', minHeight: 0,
    display: 'flex', alignItems: 'center', justifyContent: 'center', touchAction: 'none', cursor: 'grab' },
  // v2 다크 지도 (오르세4 전용)
  floorImgBoxV2: { background: 'radial-gradient(120% 90% at 50% 28%,#1c1c20 0%,#151518 55%,#0f0f12 100%)' },
  floorImgV2: { filter: 'invert(0.92) hue-rotate(180deg) brightness(0.95) contrast(1.05)' },
  mapRoundV2: { width: 44, height: 44, borderRadius: 9999, background: 'rgba(28,28,32,0.92)',
    border: '1.5px solid rgba(255,255,255,0.12)', color: '#c8c8ce', boxShadow: '0 4px 10px rgba(0,0,0,0.35)' },
  mapRoundV2On: { border: '1.5px solid #f2760f', color: '#f2760f' },
  floorPillV2: { background: 'rgba(22,22,26,0.94)', border: '1px solid rgba(255,255,255,0.1)', padding: 6, gap: 2,
    boxShadow: '0 6px 16px rgba(0,0,0,0.35)' },
  floorPillItemV2: { padding: '9px 12px', borderRadius: 9999, color: '#a1a1aa', fontSize: 13, width: 44 },
  floorPillItemV2On: { background: '#fef0e4', color: '#f2760f' },

  zoomReset: { position: 'absolute', right: 10, bottom: 66, zIndex: 6, padding: '8px 12px', borderRadius: 8,
    background: TXT_DEFAULT, color: W, fontSize: 13, fontWeight: 700, border: 'none',
    cursor: 'pointer', boxShadow: '0 2px 8px rgba(0,0,0,0.28)' },

  // 층 선택 pill
  floorPill: { display: 'flex', flexDirection: 'column',
    background: BG_PAGE, borderRadius: 9999, boxShadow: '0 2px 8px rgba(0,0,0,0.2)', overflow: 'hidden' },
  floorPillItem: { padding: '10px 16px', border: 'none', background: 'transparent', color: TXT_SUBTLE,
    fontSize: 14, fontWeight: 700, cursor: 'pointer', textAlign: 'center', whiteSpace: 'nowrap' },
  floorPillItemOn: { color: ORANGE },
  floorCanvas: { position: 'relative', width: '100%', lineHeight: 0 },
  floorImg: { display: 'block', width: '100%', height: 'auto' },
  floorPlaceholder: { position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center',
    justifyContent: 'center', gap: 8, color: TXT_DISABLED },
  floorPhIcon: { fontSize: 40 },
  floorPhTxt: { fontSize: 15, fontWeight: 700, color: TXT_SUBTLE },
  floorPhSub: { fontSize: 12, color: TXT_DISABLED },
  routeSvg: { position: 'absolute', inset: 0, width: '100%', height: '100%', zIndex: 1, pointerEvents: 'none' },
  pinTooltipWrap: { position: 'absolute', bottom: '100%', left: '50%', transform: 'translateX(-50%)',
    marginBottom: 8, display: 'flex', flexDirection: 'column', alignItems: 'center', pointerEvents: 'none' },
  // 구글지도 툴팁(iwContent)과 동일하게: 12px/700, padding 6px 10px, radius 6, 그림자 없음.
  // lineHeight 'normal' 명시 — 전역 :root의 145%(index.css) 상속으로 pill이 높아지는 것 방지.
  pinTooltip: { whiteSpace: 'nowrap', background: ORANGE, color: W, fontSize: 12, fontWeight: 700,
    lineHeight: 'normal', padding: '6px 10px', borderRadius: 6 },
  pinStartBubble: { whiteSpace: 'nowrap', background: ORANGE, color: W, fontSize: 13, fontStyle: 'italic', fontWeight: 700,
    padding: '6px 12px', borderRadius: 20, boxShadow: '0 2px 6px rgba(0,0,0,0.3)', letterSpacing: '0.5px' },
  pinTooltipArrow: { width: 0, height: 0, borderLeft: '6px solid transparent', borderRight: '6px solid transparent',
    borderTop: `6px solid ${ORANGE}` },
  pin: { position: 'absolute', zIndex: 2, transform: 'translate(-50%,-50%)', width: 26, height: 26,
    borderRadius: '50%', background: '#64748B', color: W, fontSize: 13, fontWeight: 700, border: `2px solid ${BG_PAGE}`,
    boxShadow: '0 2px 6px rgba(0,0,0,0.3)', cursor: 'pointer', display: 'flex', alignItems: 'center',
    justifyContent: 'center', lineHeight: 1 },
  pinOn: { background: ORANGE, transform: 'scale(1.3)', zIndex: 4 },
  pinVisited: { background: TXT_DISABLED, border: `2px solid ${BG_MUTED}`, opacity: 0.7 },
  pinPlayingBadge: { position: 'absolute', bottom: '100%', left: '50%', transform: 'translateX(-50%)',
    marginBottom: 3, display: 'flex', alignItems: 'flex-end', gap: 2, padding: '0 1px' },
  pinEqBar: { width: 3, background: W, borderRadius: 2, display: 'inline-block',
    transformOrigin: 'bottom', animation: 'eq 0.7s ease-in-out infinite', flexShrink: 0,
    filter: 'drop-shadow(0 1px 2px rgba(0,0,0,0.4))' },
  foot: { position: 'absolute', zIndex: 3, transform: 'translate(-50%,-50%)', fontSize: 15, lineHeight: 1,
    filter: 'drop-shadow(0 1px 2px rgba(0,0,0,0.35))', pointerEvents: 'none' },
  crossFloor: { position: 'absolute', zIndex: 5, transform: 'translate(-50%,-180%)', whiteSpace: 'nowrap',
    background: ORANGE, color: W, fontSize: 11, fontWeight: 600, padding: '4px 8px', borderRadius: 9999,
    boxShadow: '0 2px 6px rgba(0,0,0,0.3)', pointerEvents: 'none' },

  roomChips: { display: 'flex', gap: 8, overflowX: 'auto', padding: '10px 8px', flexShrink: 0, background: '#fff' },
  roomChip: { flexShrink: 0, width: 36, height: 36, borderRadius: '50%', border: '1px solid #e0e0e6', background: '#fff',
    color: '#555', fontSize: 14, fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center',
    justifyContent: 'center', padding: 0 },
  roomChipOn: { background: ORANGE, border: `1px solid ${ORANGE}`, color: '#fff' },
  roomChipVisited: { background: '#dfe1e8', border: '1px solid #dfe1e8', color: '#9298a6' },

  stripHeader: { display: 'flex', alignItems: 'center', gap: 6, padding: '10px 4px 6px', flexShrink: 0 },
  stripPinIcon: { display: 'flex', alignItems: 'center', flexShrink: 0 },
  stripRoomName: { fontSize: 15, fontWeight: 700, color: TXT_STRONG, flex: 1 },
  stripHeaderCount: { fontSize: 13, fontWeight: 500, color: TXT_SUBTLE, flexShrink: 0 },
  strip: { display: 'flex', gap: 2, overflowX: 'auto', padding: '4px 0 8px', flexShrink: 0 },
  stripCard: { flexShrink: 0, width: 92, background: 'none', border: 'none', padding: 0, cursor: 'pointer' },
  stripThumb: { position: 'relative', width: 92, height: 92, borderRadius: 10, overflow: 'hidden', background: BG_MUTED,
    border: '2px solid transparent' },
  stripThumbOn: { border: `3px solid ${ORANGE}`, boxShadow: `0 0 0 2px ${ORANGE_LIGHT}` },
  stripNo: { position: 'absolute', top: 4, left: 4, zIndex: 2, minWidth: 16, height: 16, padding: '0 4px',
    borderRadius: 8, background: 'rgba(0,0,0,0.6)', color: '#fff', fontSize: 10, fontWeight: 700,
    display: 'flex', alignItems: 'center', justifyContent: 'center' },
  stripNoOn: { background: ORANGE },
  stripEqBadge: { position: 'absolute', top: 5, right: 5, display: 'flex', alignItems: 'flex-end', gap: 2, background: 'rgba(0,0,0,0.42)', borderRadius: 4, padding: '4px 5px' },
  stripHeart: { position: 'absolute', bottom: 4, right: 4, background: 'none', border: 'none', color: 'rgba(255,255,255,0.8)', fontSize: 16, cursor: 'pointer', padding: 2, lineHeight: 1 },
  stripHeartOn: { position: 'absolute', bottom: 4, right: 4, background: 'none', border: 'none', color: ORANGE, fontSize: 16, cursor: 'pointer', padding: 2, lineHeight: 1 },
  nowPlay: { position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center',
    background: 'rgba(0,0,0,0.25)' },
  nowPlayBtn: { width: 36, height: 36, borderRadius: '50%', background: ORANGE,
    display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: '0 2px 8px rgba(0,0,0,0.3)' },
  eqBar: { width: 3, background: '#fff', borderRadius: 2, transformOrigin: 'bottom',
    animation: 'eq 0.8s ease-in-out infinite' },
  nowPlayTxt: { position: 'absolute', bottom: 5, fontSize: 9, fontWeight: 700, color: '#fff', letterSpacing: 0.5 },

  nextStopCard: { border: 'none', borderRadius: 10, padding: '0 0 2px', display: 'flex',
    flexDirection: 'column', alignItems: 'center', justifyContent: 'flex-start', gap: 0 },
  nextStopCardDisabled: {},
  nextStopThumb: { width: 92, height: 72, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  nextStopCircle: { width: 40, height: 40, borderRadius: '50%', background: ORANGE, color: W,
    fontSize: 26, fontWeight: 700, display: 'flex', alignItems: 'center', justifyContent: 'center',
    lineHeight: 1, paddingLeft: 3 },
  nextStopCircleDisabled: { background: BORDER_DEFAULT },
  prevStopCircle: { width: 40, height: 40, borderRadius: '50%', background: BORDER_DEFAULT, color: TXT_STRONG,
    fontSize: 26, fontWeight: 700, display: 'flex', alignItems: 'center', justifyContent: 'center',
    lineHeight: 1, paddingRight: 3 },
  nextStopLabel: { fontSize: 11, color: TXT_SUBTLE, marginTop: 2 },
  nextStopName: { fontSize: 13, fontWeight: 700, color: TXT_STRONG, marginTop: 1,
    whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', maxWidth: 88 },

  // 핀 스트립 — 재생 어포던스는 썸네일에, 이동은 강등 (개수 무관 동일 구조)
  // 헤더: 장소명(+트랙 수) / 전환 라벨
  stripHead: { display: 'flex', alignItems: 'baseline', gap: 8, padding: '2px 2px 6px' },
  stripHeadName: { fontSize: 14, fontWeight: 700, color: TXT_STRONG,
    whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  stripHeadCount: { fontSize: 12, fontWeight: 500, color: TXT_SUBTLE, flexShrink: 0 },

  // 트랙 썸네일 (항상 노출, 제목 없음)
  stripCardSm: { flexShrink: 0, width: 68, background: 'none', border: 'none', padding: 0, cursor: 'pointer' },
  stripThumbSm: { position: 'relative', width: 68, height: 68, borderRadius: 10, overflow: 'hidden',
    background: BG_MUTED, border: '2px solid transparent' },
  // 잠금(미구매) 상태: 딤 + 중앙 자물쇠. 좋아요 버튼(우하단)과 안 겹치게 중앙 배치
  stripLockOverlay: { position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center',
    background: 'rgba(0,0,0,0.34)', pointerEvents: 'none' },
  stripLockBadge: { width: 26, height: 26, borderRadius: '50%', background: 'rgba(0,0,0,0.55)',
    display: 'flex', alignItems: 'center', justifyContent: 'center' },
  // 이동 유도 핀(전환) — 콘텐츠 아님. 썸네일 크기 대신 낮은 가로 필 버튼
  stripMoveBtn: { display: 'flex', alignItems: 'center', gap: 10, width: '100%', textAlign: 'left',
    background: SUB_COLOR, color: W, border: 'none', borderRadius: 12, padding: '12px 14px', cursor: 'pointer', marginTop: 2 },
  stripMoveIcon: { width: 28, height: 28, borderRadius: 8, background: 'rgba(255,255,255,0.18)',
    display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  stripMoveLabel: { flex: 1, minWidth: 0, fontSize: 14, fontWeight: 700,
    whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  stripMoveSub: { fontWeight: 400, color: 'rgba(255,255,255,0.85)' },
  stripMoveChev: { fontSize: 22, fontWeight: 700, lineHeight: 1, flexShrink: 0 },

  // 얇은 이동 보조 줄
  stripNavRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginTop: 6, minHeight: 30 },
  stripNavItem: { display: 'flex', alignItems: 'center', gap: 5, background: 'none', border: 'none',
    color: TXT_SUBTLE, fontSize: 12, fontWeight: 600, cursor: 'pointer', padding: '6px 2px', maxWidth: '48%', overflow: 'hidden' },
  stripNavPrev: { marginRight: 'auto' },
  stripNavNext: { marginLeft: 'auto' },
  stripNavChev: { fontSize: 18, fontWeight: 700, lineHeight: 1, color: TXT_SUBTLE, flexShrink: 0 },
  stripNavName: { color: TXT_DEFAULT, fontWeight: 700, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  stripNavItemOff: { color: TXT_DISABLED, cursor: 'default' },
  stripNavChevOff: { color: TXT_DISABLED },

  listFilter: { height: 34, padding: '0 12px', borderRadius: 9999, border: `1px solid ${BORDER_DEFAULT}`,
    background: BG_PAGE, color: TXT_STRONG, fontSize: 13, fontWeight: 400, cursor: 'pointer',
    display: 'flex', alignItems: 'center', outline: 'none' },
  listFilterOn: { background: W, border: `1.5px solid ${ORANGE}`, color: ORANGE, fontWeight: 700 },
  listBody: { flex: 1, overflow: 'auto', padding: '4px 8px 16px' },
  listGroupHeader: { fontSize: 14, fontWeight: 700, color: TXT_STRONG, padding: '16px 4px 8px', textAlign: 'left' },
  listGroupBox: { background: W, borderRadius: 12, overflow: 'hidden' },
  floorDrop: { margin: '0 8px 8px', borderRadius: 12, border: `1px solid ${BORDER_DEFAULT}`,
    background: BG_PAGE, overflow: 'hidden', boxShadow: '0 4px 16px rgba(0,0,0,0.10)' },
  floorDropItem: { display: 'block', width: '100%', padding: '13px 16px', textAlign: 'left',
    background: 'none', border: 'none', borderBottom: `1px solid ${BG_MUTED}`,
    fontSize: 14, fontWeight: 500, color: TXT_DEFAULT, cursor: 'pointer' },
  floorDropItemOn: { color: ORANGE, fontWeight: 700, background: ORANGE_LIGHT },
  floorModalItem: { display: 'block', width: '100%', padding: '16px 20px', textAlign: 'left',
    background: 'none', border: 'none', borderBottom: `1px solid ${BG_MUTED}`,
    fontSize: 15, fontWeight: 500, color: TXT_DEFAULT, cursor: 'pointer', outline: 'none' },
  floorModalItemOn: { color: ORANGE, fontWeight: 700, background: ORANGE_LIGHT },
  listItem: { display: 'flex', alignItems: 'center', gap: 12, width: '100%', padding: '12px 12px', borderRadius: 0,
    border: 'none', borderBottom: '1px solid #EBEBEB', background: 'none', cursor: 'pointer' },
  listItemOn: {},
  listThumb: { position: 'relative', width: 92, height: 92, borderRadius: 10, overflow: 'hidden',
    flexShrink: 0, background: BG_MUTED, border: '2px solid transparent' },
  listThumbOn: { border: `2px solid ${ORANGE}` },
  listThumbNowPlay: { position: 'absolute', inset: 0, display: 'flex', alignItems: 'center',
    justifyContent: 'center', gap: 2, background: 'rgba(0,0,0,0.42)' },
  listTitle: { fontSize: 15, fontWeight: 600, color: TXT_STRONG },
  listSub: { fontSize: 13, color: TXT_SUBTLE, marginTop: 2 },
  listHeartOff: { background: 'none', border: 'none', color: BORDER_DEFAULT, fontSize: 20,
    cursor: 'pointer', flexShrink: 0, padding: '4px 8px', lineHeight: 1 },
  listHeartOn: { background: 'none', border: 'none', color: ORANGE, fontSize: 20,
    cursor: 'pointer', flexShrink: 0, padding: '4px 8px', lineHeight: 1 },

  dim: { position: 'absolute', inset: 0, zIndex: 50, background: 'rgba(0,0,0,0.50)' },
  overlaySheet: { position: 'absolute', left: 0, right: 0, bottom: 0, height: '60%', zIndex: 51,
    background: BG_PAGE, borderRadius: '16px 16px 0 0', display: 'flex', flexDirection: 'column',
    boxShadow: '0 -4px 12px rgba(0,0,0,0.30)' },
  overlayHandle: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: 28, flexShrink: 0 },
  overlayHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '0 20px 12px', borderBottom: `1px solid ${BORDER_DEFAULT}`, flexShrink: 0 },
  overlayTitle: { fontSize: 20, fontWeight: 600, color: TXT_STRONG },
  overlayClose: { background: 'none', border: 'none', fontSize: 24, color: TXT_DEFAULT, cursor: 'pointer',
    width: 44, height: 44, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  overlayBody: { flex: 1, overflow: 'auto', padding: '20px 24px' },
  overlayEmpty: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
    height: '100%' },
  scriptBody: { lineHeight: 1.6 },
  scriptTitle: { fontSize: 20, fontWeight: 600, color: TXT_STRONG, margin: '0 0 16px' },
  scriptText: { fontSize: 16, color: TXT_DEFAULT, margin: 0, whiteSpace: 'pre-wrap', lineHeight: 1.6 },

  settingsBody: { display: 'flex', flexDirection: 'column', gap: 20, paddingBottom: 20 },
  settingsRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  settingsLabel: { fontSize: 16, fontWeight: 600, color: TXT_STRONG },
  settingsValue: { fontSize: 15, fontWeight: 400, color: TXT_SUBTLE },
  toggleTrack: { width: 44, height: 24, borderRadius: 9999, background: BORDER_DEFAULT, border: 'none',
    cursor: 'pointer', position: 'relative', padding: 0 },
  toggleTrackOn: { background: ORANGE },
  toggleHandle: { width: 20, height: 20, borderRadius: '50%', background: W, position: 'absolute',
    top: 2, left: 2, transition: 'left 150ms ease' },
  toggleHandleOn: { left: 22 },
  speedRow: { display: 'flex', gap: 8, flexWrap: 'wrap' },
  speedBtn: { padding: '8px 16px', borderRadius: 8, border: `1px solid ${BORDER_DEFAULT}`,
    background: BG_PAGE, color: TXT_STRONG, fontSize: 14, fontWeight: 600, cursor: 'pointer' },
  speedBtnOn: { background: ORANGE, borderColor: ORANGE, color: W },
};

export { styles, ORANGE, TXT_DEFAULT, TXT_SUBTLE, BORDER_DEFAULT };
