// — Design Tokens —
const W = '#FFFFFF';
const ORANGE = '#FF730D';
const ORANGE_LIGHT = '#FFF3EC';
const TXT_STRONG = '#1A1A1A';
const TXT_DEFAULT = '#3A3A3A';
const TXT_SUBTLE = '#8A8A8A';
const BG_PAGE = '#FFFFFF';
const BG_MUTED = '#F2F4F7';
const BORDER_DEFAULT = '#D1D1D1';
const PLAYER_BG = '#000000';
const FONT = "'Pretendard Variable', 'Pretendard', -apple-system, BlinkMacSystemFont, sans-serif";

const styles = {
  root: { position: 'relative', height: '100dvh', minHeight: '100vh', background: PLAYER_BG, overflow: 'hidden', color: W, fontFamily: FONT },

  player: { position: 'absolute', top: 0, left: 0, right: 0, display: 'flex', flexDirection: 'column', background: PLAYER_BG, overflow: 'hidden' },
  topBar: { position: 'relative', zIndex: 2, display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 16px', background: 'linear-gradient(rgba(0,0,0,0.45), transparent)' },
  iconBtn: { background: 'none', border: 'none', color: W, fontSize: 24, lineHeight: 1, cursor: 'pointer', width: 32, height: 32, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 0 },
  topRight: { display: 'flex', alignItems: 'center', gap: 8 },
  gearBtn: { background: 'none', border: 'none', color: W, fontSize: 18, width: 36, height: 36, borderRadius: 9999, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' },

  fullWrap: { flex: 1, display: 'flex', flexDirection: 'column', padding: '4px 20px 16px', overflow: 'auto' },
  artBig: { position: 'relative', width: '80%', aspectRatio: '1 / 1', margin: '6px auto 0', borderRadius: 8, overflow: 'hidden', background: '#2a2a2a', boxShadow: '0 12px 40px rgba(0,0,0,0.6)' },
  artImg: { width: '100%', height: '100%', objectFit: 'contain' },
  coverImg: { position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover' },
  containImg: { position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'contain' },
  miniBlurBg: { position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover', filter: 'blur(28px)', transform: 'scale(1.2)', opacity: 0.5 },
  imgFallback: { width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'linear-gradient(135deg,#2a2a32,#16161c)' },
  imgFallbackIcon: { fontSize: 40, opacity: 0.5 },
  playOverlay: { position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 40, color: 'rgba(255,255,255,0.85)', textShadow: '0 2px 12px rgba(0,0,0,0.6)', pointerEvents: 'none' },
  badge: { position: 'absolute', top: 8, left: 8, background: ORANGE, color: W, fontSize: 11, fontWeight: 600, padding: '3px 8px', borderRadius: 9999 },
  countRow: { textAlign: 'center', margin: '12px 0 4px' },
  count: { fontSize: 13, color: TXT_SUBTLE },
  titleRow: { display: 'flex', alignItems: 'flex-start', gap: 12, marginTop: 4 },
  title: { fontSize: 20, fontWeight: 600, color: W, margin: 0, lineHeight: 1.45 },
  subtitle: { fontSize: 13, color: TXT_SUBTLE, margin: '4px 0 0', lineHeight: 1.5 },
  heart: { background: 'none', border: 'none', fontSize: 24, cursor: 'pointer', lineHeight: 1, flexShrink: 0 },

  chips: { display: 'flex', gap: 8, marginTop: 16, flexWrap: 'wrap' },
  chip: { fontSize: 13, color: W, background: 'rgba(255,255,255,0.15)', padding: '8px 12px', borderRadius: 8, whiteSpace: 'nowrap', border: 'none', cursor: 'pointer', backdropFilter: 'blur(10px)', WebkitBackdropFilter: 'blur(10px)' },
  chipIcon: { color: W, background: 'none', border: 'none', width: 36, height: 36, borderRadius: 9999, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' },

  progWrap: { marginTop: 16 },
  progBar: { position: 'relative', height: 4, background: 'rgba(255,255,255,0.15)', borderRadius: 9999, cursor: 'pointer' },
  progFill: { position: 'absolute', top: 0, left: 0, height: '100%', background: ORANGE, borderRadius: 9999 },
  progThumb: { position: 'absolute', top: '50%', transform: 'translate(-50%,-50%)', width: 12, height: 12, borderRadius: '50%', background: '#fff', pointerEvents: 'none' },
  timeRow: { display: 'flex', justifyContent: 'space-between', marginTop: 7 },
  time: { fontSize: 12, color: TXT_SUBTLE },

  controls: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 20, marginTop: 16 },
  ctrlSide: { background: 'none', border: 'none', color: TXT_SUBTLE, fontSize: 20, cursor: 'pointer', display: 'flex', alignItems: 'center' },
  ctrlNum: { fontSize: 9, bottom: 0 },
  ctrl: { background: 'none', border: 'none', color: W, fontSize: 22, cursor: 'pointer' },
  ctrlBig: { background: 'none', border: 'none', color: W, fontSize: 26, cursor: 'pointer' },
  play: { width: 48, height: 48, borderRadius: '50%', background: W, color: PLAYER_BG, fontSize: 18, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', border: 'none' },
  playBig: { width: 64, height: 64, borderRadius: '50%', background: W, color: PLAYER_BG, fontSize: 24, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', border: 'none' },
  playDisabled: { background: 'rgba(255,255,255,0.25)', color: 'rgba(255,255,255,0.6)' },

  bottomBtns: { display: 'flex', gap: 8, marginTop: 'auto', paddingTop: 20 },
  bottomBtn: { flex: 1, padding: '14px', borderRadius: 12, background: 'rgba(255,255,255,0.15)', border: 'none', color: W, fontSize: 15, fontWeight: 600, cursor: 'pointer' },

  compactBar: { display: 'flex', alignItems: 'center', gap: 12, padding: '8px 16px', background: PLAYER_BG, flex: 1, overflow: 'hidden' },
  compactThumb: { position: 'relative', width: 52, height: 52, borderRadius: 8, overflow: 'hidden', flexShrink: 0, background: '#222' },
  compactTitleWrap: { flex: 1, overflow: 'hidden' },
  compactTitle: { display: 'inline-block', fontSize: 16, fontWeight: 700, color: W, whiteSpace: 'nowrap', animation: 'marquee 8s linear infinite', animationDelay: '2s' },
  compactControls: { display: 'flex', alignItems: 'center', gap: 8, flexShrink: 0 },
  compactPlayBtn: { width: 40, height: 40, borderRadius: '50%', background: 'rgba(255,255,255,0.15)', color: W, fontSize: 16, border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  compactDownBtn: { width: 40, height: 40, borderRadius: '50%', background: 'rgba(255,255,255,0.15)', color: W, fontSize: 24, border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', lineHeight: 1 },

  miniWrap: { position: 'absolute', inset: 0, zIndex: 1, background: PLAYER_BG },
  miniBar: { position: 'absolute', left: 0, right: 0, bottom: 0, display: 'flex', alignItems: 'center', padding: '12px 16px', gap: 12, background: 'linear-gradient(transparent, rgba(0,0,0,0.7))' },
  miniBarInfo: { flex: 1, display: 'flex', flexDirection: 'column', gap: 2, overflow: 'hidden', textAlign: 'left' },
  miniBarTitle: { fontSize: 15, fontWeight: 700, color: W, whiteSpace: 'nowrap', textShadow: '0 1px 4px rgba(0,0,0,0.5)', display: 'inline-block', animation: 'marquee 8s linear infinite', animationDelay: '2s' },
  miniBarSub: { fontSize: 12, color: 'rgba(255,255,255,0.7)', whiteSpace: 'nowrap' },
  miniBarControls: { display: 'flex', alignItems: 'center', gap: 8, flexShrink: 0 },
  miniBarBtn: { background: 'none', border: 'none', color: W, fontSize: 20, cursor: 'pointer', width: 36, height: 36, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  miniBarPlay: { width: 40, height: 40, borderRadius: '50%', background: W, color: PLAYER_BG, fontSize: 16, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', border: 'none' },

  sheet: { position: 'absolute', left: 0, right: 0, bottom: 0, background: BG_MUTED, borderRadius: '16px 16px 0 0', display: 'flex', flexDirection: 'column', overflow: 'hidden', boxShadow: '0 -4px 12px rgba(0,0,0,0.3)' },
  handleZone: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: 20, cursor: 'grab', touchAction: 'none', flexShrink: 0 },
  sheetTabBar: { display: 'flex', alignItems: 'center', padding: '6px 14px 6px', flexShrink: 0 },
  sheetTabToggleFixed: { position: 'absolute', right: 16, bottom: 16, zIndex: 20, display: 'flex',
    background: BG_PAGE, borderRadius: 9999, padding: 3, gap: 2,
    border: `1px solid ${BORDER_DEFAULT}`, boxShadow: '0 2px 8px rgba(0,0,0,0.15)' },
  sheetTabToggle: { display: 'flex', background: BG_MUTED, borderRadius: 9999, padding: 3, gap: 2,
    border: `1px solid ${BORDER_DEFAULT}` },
  sheetTabBtn: { height: 34, padding: '0 12px', borderRadius: 9999, border: 'none', background: 'transparent',
    fontSize: 13, fontWeight: 600, color: TXT_SUBTLE, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  sheetTabBtnOn: { background: '#1a1a1a', color: '#fff', boxShadow: '0 1px 6px rgba(0,0,0,0.2)' },
  grabber: { width: 52, height: 6, borderRadius: 9999, background: BORDER_DEFAULT },

  sheetBody: { position: 'relative', flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minHeight: 0 },
  mapBox: { position: 'relative', flex: 1, overflow: 'hidden', minHeight: 0, background: '#E3E3E3' },
  mapTopBar: { position: 'absolute', top: 10, left: 10, right: 10, zIndex: 5, display: 'flex', gap: 8 },
  tocBtn: { height: 34, padding: '0 12px', borderRadius: 9999, background: TXT_STRONG, color: W, fontSize: 13, fontWeight: 700, border: 'none', cursor: 'pointer', boxShadow: '0 2px 8px rgba(0,0,0,0.28)', display: 'flex', alignItems: 'center', outline: 'none' },
  mapTopBtn: { height: 34, padding: '0 12px', borderRadius: 9999, border: `1px solid ${BORDER_DEFAULT}`, background: BG_PAGE, color: TXT_STRONG, fontSize: 13, fontWeight: 600, cursor: 'pointer', boxShadow: '0 2px 8px rgba(0,0,0,0.08)', display: 'flex', alignItems: 'center', outline: 'none' },
  mapTopBtnOn: { background: W, border: `1.5px solid ${ORANGE}`, color: ORANGE },

  navModalBackdrop: { position: 'fixed', inset: 0, zIndex: 9999, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.4)' },
  navModal: { background: '#f2f2f7', borderRadius: 14, width: 270, overflow: 'hidden' },
  navModalText: { margin: 0, padding: '20px 16px 16px', textAlign: 'center', fontSize: 14, color: '#000', lineHeight: 1.5 },
  navModalDivider: { height: 1, background: 'rgba(0,0,0,0.15)' },
  navModalBtns: { display: 'flex' },
  navModalBtnDivider: { width: 1, background: 'rgba(0,0,0,0.15)' },
  navModalCancel: { flex: 1, padding: '12px 0', border: 'none', background: 'none', fontSize: 17, color: '#007aff', cursor: 'pointer' },
  navModalConfirm: { flex: 1, padding: '12px 0', border: 'none', background: 'none', fontSize: 17, fontWeight: 600, color: '#007aff', cursor: 'pointer' },
  stripOverlay: { position: 'absolute', left: 0, right: 0, bottom: 0, zIndex: 5, padding: '0 16px 16px', background: 'linear-gradient(transparent, rgba(255,255,255,1) 80%, rgb(255,255,255) 100%)' },
  pinActionBar: { display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: 8, padding: '8px 0 4px' },
  myLocationBtn: { width: 36, height: 36, borderRadius: '50%', border: `1px solid ${BORDER_DEFAULT}`, background: BG_PAGE, color: TXT_STRONG, cursor: 'pointer', boxShadow: '0 2px 8px rgba(0,0,0,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center', outline: 'none', flexShrink: 0 },
  myLocationBtnOn: { background: BG_PAGE, border: `1.5px solid ${ORANGE}`, color: ORANGE },
  strip: { display: 'flex', gap: 2, overflowX: 'auto', padding: '4px 0 8px', flexShrink: 0 },
  stripCard: { flexShrink: 0, width: 92, background: 'none', border: 'none', padding: 0, cursor: 'pointer' },
  stripThumb: { position: 'relative', width: 92, height: 92, borderRadius: 10, overflow: 'hidden', background: BG_MUTED, border: '2px solid transparent' },
  stripThumbOn: { border: `3px solid ${ORANGE}`, boxShadow: `0 0 0 2px ${ORANGE_LIGHT}` },
  stripName: { fontSize: 12, color: TXT_DEFAULT, marginTop: 4, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', textAlign: 'left' },
  stripNameOn: { color: ORANGE, fontWeight: 700 },
  nowPlay: { position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.25)' },
  nowPlayBtn: { width: 36, height: 36, borderRadius: '50%', background: ORANGE, display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: '0 2px 8px rgba(0,0,0,0.3)' },

  nextStopCard: { border: 'none', borderRadius: 10, padding: '0 0 2px', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'flex-start', gap: 0 },
  nextStopThumb: { width: 92, height: 72, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  nextStopCircle: { width: 40, height: 40, borderRadius: '50%', background: ORANGE, color: W, fontSize: 26, fontWeight: 700, display: 'flex', alignItems: 'center', justifyContent: 'center', lineHeight: 1, paddingLeft: 3 },
  prevStopCircle: { width: 40, height: 40, borderRadius: '50%', background: BORDER_DEFAULT, color: TXT_STRONG, fontSize: 26, fontWeight: 700, display: 'flex', alignItems: 'center', justifyContent: 'center', lineHeight: 1, paddingRight: 3 },
  nextStopLabel: { fontSize: 11, color: TXT_SUBTLE, marginTop: 2 },
  nextStopName: { fontSize: 13, fontWeight: 700, color: TXT_STRONG, marginTop: 1, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', maxWidth: 88 },

  listWrap: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minHeight: 0 },
  listHeader: { flexShrink: 0, background: BG_MUTED },
  listTopBarOuter: { display: 'flex', alignItems: 'center', padding: '10px 12px 6px',
    background: BG_MUTED, gap: 4 },
  listTopBar: { display: 'flex', alignItems: 'center', gap: 8, flex: 1,
    overflowX: 'auto', flexWrap: 'nowrap', WebkitOverflowScrolling: 'touch',
    scrollbarWidth: 'none', msOverflowStyle: 'none' },
  listSecondBar: { display: 'flex', alignItems: 'center', gap: 8, padding: '0 12px 8px', background: BG_MUTED, justifyContent: 'flex-end' },
  tocBtnList: { height: 34, padding: '0 12px', borderRadius: 9999, background: TXT_STRONG, color: W, fontSize: 13, fontWeight: 700, border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', outline: 'none' },
  listFilter: { height: 34, padding: '0 12px', borderRadius: 9999, border: `1px solid ${BORDER_DEFAULT}`, background: BG_PAGE, color: TXT_STRONG, fontSize: 13, fontWeight: 400, cursor: 'pointer', display: 'flex', alignItems: 'center', outline: 'none' },
  listFilterOn: { background: W, border: `1.5px solid ${ORANGE}`, color: ORANGE, fontWeight: 700 },
  searchIconBtn: { width: 36, height: 36, border: 'none', background: 'none', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', flexShrink: 0, outline: 'none' },
  searchIconAbsBtn: { flexShrink: 0, width: 36, height: 36, border: 'none', background: 'none', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', outline: 'none' },
  searchBar: { flex: 1, display: 'flex', alignItems: 'center', gap: 8, height: 38, border: `1.5px solid ${ORANGE}`, borderRadius: 9999, padding: '0 14px', background: BG_PAGE },
  searchInput: { flex: 1, border: 'none', outline: 'none', background: 'none', fontSize: 14, color: TXT_STRONG, fontFamily: 'inherit' },
  searchCancelBtn: { flexShrink: 0, border: 'none', background: 'none', fontSize: 14, fontWeight: 500, color: TXT_DEFAULT, cursor: 'pointer', outline: 'none', padding: '0 4px' },
  listBody: { flex: 1, overflow: 'auto', padding: '4px 8px 16px' },
  listGroupBox: { background: W, borderRadius: 12, overflow: 'hidden' },
  listItem: { display: 'flex', alignItems: 'center', gap: 12, width: '100%', padding: '12px 12px', borderRadius: 0, border: 'none', borderBottom: '1px solid #EBEBEB', background: 'none', cursor: 'pointer' },
  listItemOn: {},
  listThumb: { position: 'relative', width: 92, height: 92, borderRadius: 10, overflow: 'hidden', flexShrink: 0, background: BG_MUTED, border: '2px solid transparent' },
  listThumbOn: { border: `2px solid ${ORANGE}` },
  listThumbNowPlay: { position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 2, background: 'rgba(0,0,0,0.42)' },
  listThumbDim: { position: 'absolute', inset: 0, background: 'rgba(0,0,0,0.30)', borderRadius: 8 },
  listThumbEqBadge: { position: 'absolute', top: 5, right: 5, display: 'flex', alignItems: 'flex-end', gap: 2, background: 'rgba(0,0,0,0.42)', borderRadius: 4, padding: '4px 5px' },
  eqBar: { width: 3, background: '#fff', borderRadius: 2, transformOrigin: 'bottom', animation: 'eq 0.8s ease-in-out infinite' },
  stripEqBadge: { position: 'absolute', top: 5, right: 5, display: 'flex', alignItems: 'flex-end', gap: 2, background: 'rgba(0,0,0,0.42)', borderRadius: 4, padding: '4px 5px' },
  stripHeart: { position: 'absolute', bottom: 4, right: 4, background: 'none', border: 'none', color: 'rgba(255,255,255,0.8)', fontSize: 16, cursor: 'pointer', padding: 2, lineHeight: 1 },
  stripHeartOn: { position: 'absolute', bottom: 4, right: 4, background: 'none', border: 'none', color: ORANGE, fontSize: 16, cursor: 'pointer', padding: 2, lineHeight: 1 },
  listTitle: { fontSize: 15, fontWeight: 600, color: TXT_STRONG },
  listSub: { fontSize: 13, color: TXT_SUBTLE, marginTop: 2 },
  listHeartOff: { background: 'none', border: 'none', color: BORDER_DEFAULT, fontSize: 20, cursor: 'pointer', flexShrink: 0, padding: '4px 8px', lineHeight: 1 },
  listHeartOn: { background: 'none', border: 'none', color: ORANGE, fontSize: 20, cursor: 'pointer', flexShrink: 0, padding: '4px 8px', lineHeight: 1 },

  dim: { position: 'absolute', inset: 0, zIndex: 50, background: 'rgba(0,0,0,0.50)' },
  overlaySheet: { position: 'absolute', left: 0, right: 0, bottom: 0, height: '60%', zIndex: 51, background: BG_PAGE, borderRadius: '16px 16px 0 0', display: 'flex', flexDirection: 'column', boxShadow: '0 -4px 12px rgba(0,0,0,0.30)' },
  overlayHandle: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: 28, flexShrink: 0 },
  overlayHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0 20px 12px', borderBottom: `1px solid ${BORDER_DEFAULT}`, flexShrink: 0 },
  overlayTitle: { fontSize: 20, fontWeight: 600, color: TXT_STRONG },
  overlayClose: { background: 'none', border: 'none', fontSize: 24, color: TXT_DEFAULT, cursor: 'pointer', width: 44, height: 44, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  overlayBody: { flex: 1, overflow: 'auto', padding: '20px 24px' },
  overlayEmpty: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%' },
  scriptBody: { lineHeight: 1.6 },
  scriptTitle: { fontSize: 20, fontWeight: 600, color: TXT_STRONG, margin: '0 0 16px' },
  scriptText: { fontSize: 16, color: TXT_DEFAULT, margin: 0, whiteSpace: 'pre-wrap', lineHeight: 1.6 },

  settingsBody: { display: 'flex', flexDirection: 'column', gap: 20, paddingBottom: 20 },
  settingsRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  settingsLabel: { fontSize: 16, fontWeight: 600, color: TXT_STRONG },
  settingsValue: { fontSize: 15, fontWeight: 400, color: TXT_SUBTLE },
  toggleTrack: { width: 44, height: 24, borderRadius: 9999, background: BORDER_DEFAULT, border: 'none', cursor: 'pointer', position: 'relative', padding: 0 },
  toggleTrackOn: { background: ORANGE },
  toggleHandle: { width: 20, height: 20, borderRadius: '50%', background: W, position: 'absolute', top: 2, left: 2, transition: 'left 150ms ease' },
  toggleHandleOn: { left: 22 },
};

export { styles, ORANGE, TXT_DEFAULT, TXT_SUBTLE, BORDER_DEFAULT };
